# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-inputproto
Summary:    X.Org X11 Protocol inputproto
Version:    2.0.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/inputproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-inputproto.yaml
Provides:   inputproto


%description
This extension defines a protocol to provide additional input devices management such as graphic tablets.



%prep
%setup -q -n inputproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/inputproto.pc
%{_includedir}/X11/extensions/XI.h
%{_includedir}/X11/extensions/XIproto.h
%{_includedir}/X11/extensions/XI2.h
%{_includedir}/X11/extensions/XI2proto.h
%doc %{_docdir}/inputproto/XIproto.txt
%doc %{_docdir}/inputproto/XI2proto.txt
# << files


